id: ICA96AF9A
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T14:50:32.434487'
last_modified: '2022-05-27T14:50:32.434499'
parser: null
source_metadata:
  title: 'RK: Bodhisatvapiṭaka, BMSC IV, Tibetan'
  language: bo
  base:
    f9C6A:
      title: Complete text
      base_file: f9C6A.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
